import requests
f = open(f+'building.jpg','wb')
f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/building.jpg').content)
f.close()
f = open(f+'engine.wav','wb')
f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/engine.wav').content)
f.close()
f = open(f+'version.txt','w')
f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/version.txt').text)
f.close()
f = open(f+'customcarsmain.py','w')
f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/customcarsmain.py').text)
f.close()
f = open(f+'customcarsthirdpersoncontroller.py','w')
f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/customcarsthirdpersoncontroller.py').text)
f.close()
f = open(f+'tinker.obj','w')
f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/tinker.obj').text)
f.close()
