import requests
from customcarslauncher import *
def install():
  f = open(d+'building.jpg','wb')
  f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/building.jpg').content)
  f.close()
  f = open(d+'engine.wav','wb')
  f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/engine.wav').content)
  f.close()
  f = open(d+'version.txt','w')
  f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/version.txt').text)
  f.close()
  f = open(d+'customcarsmain.py','w')
  f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/customcarsmain.py').text)
  f.close()
  f = open(d+'customcarsthirdpersoncontroller.py','w')
  f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/customcarsthirdpersoncontroller.py').text)
  f.close()
  f = open(d+'tinker.obj','w')
  f.write(requests.get('https://raw.githubusercontent.com/bestbinaryboi/customcars/main/tinker.obj').text)
  f.close()
